name: build, test and deploy

on:
  push:
    branches:
    - "**"  # run for branches
    tags:
    - "*"  # run for tags
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo
      if: startsWith(github.ref, 'refs/tags/') == false
      run: |
        echo ${{ github.ref }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Echo
      run: |
        echo ${{ github.ref }}

  promote-${{ matrix.env }}:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        env: [stage, prod]
    if: (matrix.env == 'stage' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/stage-deploy-'))) || (matrix.env == 'prod' && (startsWith(github.ref, 'refs/tags/stage-deploy-') || startsWith(github.ref, 'refs/tags/prod-deploy-')))

    steps:
    - name: Echo
      run: |
        echo ${{ github.ref }}
