name: build, test and deploy

on:
  push:
    branches:
    - "**"  # run for branches
    tags:
    - "*"  # run for tags
jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') == false

    steps:
    - name: Echo
      run: |
        echo ${{ github.ref }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Echo
      run: |
        echo ${{ github.ref }}

  promote-stage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/stage-deploy-')

    steps:
    - name: Echo
      run: |
        echo ${{ github.ref }}
  
  promote-prod:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/stage-deploy-') || startsWith(github.ref, 'refs/tags/prod-deploy-')
    
    steps:
    - name: Echo
      run: |
        echo ${{ github.ref }}
